[workspace]
authors = ["Suraj Pathak <suraj.s.pathak@gmail.com>"]
channels = ["conda-forge"]
description = "Dev environment for mahotas-pyodide"
name = "mahotas-pyodide"
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[tasks]
build = "python -m build"

build-wasm = """
docker run --rm -v $PIXI_PROJECT_ROOT:/src -w /src \
ghcr.io/pyodide/pyodide-env:20260120-chrome145-firefox146-py313 \
bash -c "export PATH=\\"\\$PATH:\\$HOME/.local/bin\\" && pip install pyodide-build build numpy && pyodide build"
"""

test-wasm = """
docker run --rm -v $PIXI_PROJECT_ROOT:/src -w /src \
ghcr.io/pyodide/pyodide-env:20260120-chrome145-firefox146-py313 \
bash -c "export PATH=\\"\\$PATH:\\$HOME/.local/bin\\" && pip install pyodide-build pytest numpy && rm -rf .venv-wasm && pyodide venv .venv-wasm && .venv-wasm/bin/pip install pytest scipy pillow && .venv-wasm/bin/pip install dist/mahotas-*.whl --force-reinstall && cd /tmp && /src/.venv-wasm/bin/pytest --pyargs mahotas.tests"
"""

[pypi-dependencies]
mahotas = { path = ".", editable = true }
setuptools = ">=75.6.0, <76"
build = ">=1.2.2.post1, <2"
pyodide-build = "*"

[dependencies]
python = "3.13.*"
numpy = ">=2.4.3,<3"
pytest = ">=9.0.2,<10"
c-compiler = ">=1.11.0,<2"
cxx-compiler = ">=1.11.0,<2"